###
# @name Get Todos
GET http://127.0.0.1:8000/todos
Authorization: Bearer {{authToken}}

###
# @name Get Todo
GET http://127.0.0.1:8000/todos/1
Authorization: Bearer {{authToken}}

###
# @name Get User
GET http://127.0.0.1:8000/users/2