###
# @name Post Todo
POST http://127.0.0.1:8000/todos
Content-Type: application/json

{
    "title": "Faire la vaiselle",
    "category": "ménage"
}


###
# @name POST User
POST http://127.0.0.1:8000/users
Content-Type: application/json


{
    "name": "test1",
    "email": "test1@mail.com",
    "password": "azertyazerty"
}

###
# @name POST Login
POST http://127.0.0.1:8000/auth/login
Content-Type: application/x-www-form-urlencoded

username=test1&password=azertyazerty